<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-09T18:47:02 IST" name="Suite" finished-at="2023-05-09T18:49:04 IST" duration-ms="122438">
    <groups>
    </groups>
    <test started-at="2023-05-09T18:47:02 IST" name="TestonChrome" finished-at="2023-05-09T18:48:09 IST" duration-ms="67518">
      <class name="TestCases.E2E_OrderTest">
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:TestCases.E2E_OrderTest@5a18cd76]" started-at="2023-05-09T18:47:02 IST" name="setUp" finished-at="2023-05-09T18:47:12 IST" duration-ms="9787" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="placeOrder()[pri:0, instance:TestCases.E2E_OrderTest@5a18cd76]" started-at="2023-05-09T18:47:12 IST" name="placeOrder" finished-at="2023-05-09T18:48:09 IST" duration-ms="57638" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- placeOrder -->
      </class> <!-- TestCases.E2E_OrderTest -->
    </test> <!-- TestonChrome -->
    <test started-at="2023-05-09T18:48:10 IST" name="TestonEdge" finished-at="2023-05-09T18:49:04 IST" duration-ms="54327">
      <class name="TestCases.E2E_negativeTest">
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:TestCases.E2E_negativeTest@7e3181aa]" started-at="2023-05-09T18:48:10 IST" name="setUp" finished-at="2023-05-09T18:48:21 IST" duration-ms="11339" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="placeOrder()[pri:0, instance:TestCases.E2E_negativeTest@7e3181aa]" started-at="2023-05-09T18:48:21 IST" name="placeOrder" finished-at="2023-05-09T18:49:04 IST" duration-ms="42608" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Assertion on Principal amount is not successfull expected [10977] but found [8713]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Assertion on Principal amount is not successfull expected [10977] but found [8713]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1264)
at TestCases.E2E_negativeTest.placeOrder(E2E_negativeTest.java:107)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- placeOrder -->
      </class> <!-- TestCases.E2E_negativeTest -->
    </test> <!-- TestonEdge -->
  </suite> <!-- Suite -->
</testng-results>
